version: "3.7"
services:
  app:
    image: "laravel/app:${TAG:-latest}"
    build:
      args:
        user: shopify
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shopify-network
  web:
    image: "laravel/web:${TAG:-latest}"
    build:
      context: ./
      dockerfile: docker-compose/nginx.dockerfile
    container_name: test-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-80}:80
      - ${SERVER_PORT_SSL:-8443}:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shopify-network
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify
      POSTGRES_DB: shopify
    ports:
      - "5432:5432"
    networks:
      - shopify-network
networks:
  shopify-network:
    driver: bridge
volumes:
  postgres_data:
