version: "3.7"
services:
  app:
    image: "laravel/app:${TAG:-latest}"
    build:
      args:
        user: shopify
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: survey_laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shopify-network
  web:
    image: "laravel/web:${TAG:-latest}"
    build:
      context: ./
      dockerfile: docker-compose/nginx.dockerfile
    container_name: survey-test-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-80}:80
      - ${SERVER_PORT_SSL:-8443}:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shopify-network
  redis:
    image: redis:latest
    container_name: survey_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_logs:/data/logs
    networks:
      - shopify-network
networks:
  shopify-network:
    driver: bridge
volumes:
  postgres_data:
